var player = {
    currencies: {
        atoms: new ExpantaNum("10"),
        atps: new ExpantaNum(0),
        atpps: new ExpantaNum(0),
        atgat: new ExpantaNum(0), // All-time gained atoms.
        bstat: new ExpantaNum(0), // Best atoms.
    },

    generators: {
        atomizers: {
            1: {
                cost: new ExpantaNum(10), // Price for one.
                initCost: new ExpantaNum(10), // Price for one, except used for if the atomizer is shown or not.

                amount: new ExpantaNum(0), // Amount bought + amount generated by other atomizers.
                amtpps: new ExpantaNum(0), // Percentage proportional to generation over amount (pps stands for percentage per second).
                
                bought: new ExpantaNum(0), // Amount bought.
                mult: new ExpantaNum(1), // Efficiency.
                per10: new ExpantaNum(2), // Per 10 atomizers base multiplier.
                shown: true,

                // Same format for all other atomizers.
            },

            2: {
                cost: new ExpantaNum(200),
                initCost: new ExpantaNum(200),

                amount: new ExpantaNum(0),
                amtpps: new ExpantaNum(0),
                
                bought: new ExpantaNum(0),
                mult: new ExpantaNum(1),
                per10: new ExpantaNum(2),
                shown: false,
            },

            3: {
                cost: new ExpantaNum("5e4"),
                initCost: new ExpantaNum("5e4"),

                amount: new ExpantaNum(0),
                amtpps: new ExpantaNum(0),
                
                bought: new ExpantaNum(0),
                mult: new ExpantaNum(1),
                per10: new ExpantaNum(2),
                shown: false,
            },

            4: {
                cost: new ExpantaNum("1e7"),
                initCost: new ExpantaNum("1e7"),
    
                amount: new ExpantaNum(0),
                amtpps: new ExpantaNum(0),

                bought: new ExpantaNum(0),
                mult: new ExpantaNum(1),
                per10: new ExpantaNum(2),
                shown: false,
            }
        }
    },

    other: {
        currentTab: {atomizers: true, options: false, statistics: false},
    }
}